# Generated by Django 3.2.7 on 2021-10-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('value', models.DecimalField(decimal_places=2, max_digits=30)),
                ('amount', models.PositiveIntegerField(max_length=30)),
                ('is_favorite', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
